[tool.ruff]
target-version = "py312"
line-length = 120

# Rules list: https://docs.astral.sh/ruff/rules/
[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "RET504", # For easier debug and better code readability this rules is disabled.
    "ANN101", # The rule has been deprecated since ruff 0.2.0.
    "ANN101", # The rule has been deprecated since ruff 0.2.0.
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.pycodestyle]
max-doc-length = 120

# Ignore rules on test.
[tool.ruff.lint.per-file-ignores]
"tests/**" = ["D", "S101", "ANN201"]

# Pyright
[tool.pyright]
venvPath = "."
venv = ".venv"
