# Ruff
[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["D", "W"]


# Ignore docstring checks on test.
[tool.ruff.per-file-ignores]
"tests/**" = ["D"]
"test_*.py" = ["D"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.pycodestyle]
max-doc-length = 120

# Pyright
[tool.pyright]
venvPath = "."
venv = ".venv"
