name: CI

on: [push, pull_request]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      # build
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      # Linting, formatting and typing
      - name: Run code quality check (ruff linter)
        run: |
          ruff ./mumar ./tests

      - name: Run code quality check (ruff format)
        run: |
          ruff format ./mumar ./tests

      - name: Run code quality check (myright)
        run: |
          pyright ./mumar ./tests

  tests:
    runs-on: ubuntu-latest

    steps:
      # build
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      # Testing and coverage.
      - name: Run tests (pytest)
        run: |
          pip install pytest-cov
          pytest tests/ --cov=./mumar

      - name: Upload coverage report (codecov)
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
