name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Run code quality check (ruff linter)
      run: |
        ruff ./mumar ./tests

    - name: Run code quality check (ruff format)
      run: |
        ruff format ./mumar ./tests

    - name: Run code quality check (myright)
      uses: jakebailey/pyright-action@v1
      with:
        version: 1.1.139

    - name: Run code quality check (pytest)
      run: |
        pytest tests/
